/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bkauto1;

public class App {

    public static void main(String[] args) {
        String[] filePaths = {"ZIMHFIFTMBF0595881126.LDD","ZIMHFIFTMBF3112254149.LDD","ZIMHFIFTMBF9315444293.LDD","ZIMHKIFTMBF5829177970.LDD","ZIMHKIFTMBF21923811826.LDD","ZIMORIFTMBF4900783475.LDD","ZIMORIFTMBF6978971779.LDD","ZIMORIFTMBF9220945364.LDD"};
        for (String filePath : filePaths) {
            
            System.out.println("Booking file: " + filePath);
            // Create an instance of the Booking class
            Booking booking = new Booking();
        
            // Call the readFile method to fill the booking instance
            booking = readEbkFile.readFile(filePath);

            booking.printBookingDetails();
            System.out.println();
            System.out.println();
        }
    }
}
